# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `faraday_middleware-multi_json` gem.
# Please instead update this file by running `bin/tapioca gem faraday_middleware-multi_json`.


# source://faraday_middleware-multi_json//lib/faraday_middleware/multi_json.rb#4
module FaradayMiddleware; end

# source://faraday_middleware-multi_json//lib/faraday_middleware/multi_json.rb#5
module FaradayMiddleware::MultiJson; end

# source://faraday_middleware-multi_json//lib/faraday_middleware/multi_json.rb#14
class FaradayMiddleware::MultiJson::EncodeJson < ::FaradayMiddleware::EncodeJson
  # @return [EncodeJson] a new instance of EncodeJson
  #
  # source://faraday_middleware-multi_json//lib/faraday_middleware/multi_json.rb#17
  def initialize(app, *_arg1); end

  # source://faraday_middleware-multi_json//lib/faraday_middleware/multi_json.rb#21
  def encode(data); end
end

# source://faraday_middleware-multi_json//lib/faraday_middleware/multi_json.rb#6
class FaradayMiddleware::MultiJson::ParseJson < ::FaradayMiddleware::ResponseMiddleware
  # source://faraday_middleware-multi_json//lib/faraday_middleware/multi_json.rb#9
  def parse(body); end
end
