# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `fasterer` gem.
# Please instead update this file by running `bin/tapioca gem fasterer`.


# pkg:gem/fasterer#lib/fasterer/version.rb:1
module Fasterer; end

# pkg:gem/fasterer#lib/fasterer/analyzer.rb:11
class Fasterer::Analyzer
  # pkg:gem/fasterer#lib/fasterer/analyzer.rb:15
  def initialize(file_path); end

  # pkg:gem/fasterer#lib/fasterer/analyzer.rb:25
  def errors; end

  # pkg:gem/fasterer#lib/fasterer/analyzer.rb:12
  def file_path; end

  # pkg:gem/fasterer#lib/fasterer/analyzer.rb:13
  def path; end

  # pkg:gem/fasterer#lib/fasterer/analyzer.rb:20
  def scan; end

  private

  # pkg:gem/fasterer#lib/fasterer/analyzer.rb:49
  def scan_by_token(token, element); end

  # pkg:gem/fasterer#lib/fasterer/analyzer.rb:78
  def scan_for_loop(element); end

  # pkg:gem/fasterer#lib/fasterer/analyzer.rb:70
  def scan_method_calls(element); end

  # pkg:gem/fasterer#lib/fasterer/analyzer.rb:62
  def scan_method_definitions(element); end

  # pkg:gem/fasterer#lib/fasterer/analyzer.rb:82
  def scan_rescue(element); end

  # pkg:gem/fasterer#lib/fasterer/analyzer.rb:31
  def traverse_sexp_tree(sexp_tree); end
end

# pkg:gem/fasterer#lib/fasterer/method_call.rb:108
class Fasterer::Argument
  # pkg:gem/fasterer#lib/fasterer/method_call.rb:111
  def initialize(element); end

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:109
  def element; end

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:115
  def type; end

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:119
  def value; end
end

# pkg:gem/fasterer#lib/fasterer/method_call.rb:2
class Fasterer::MethodCall
  # pkg:gem/fasterer#lib/fasterer/method_call.rb:12
  def initialize(element); end

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:6
  def arguments; end

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:31
  def arguments_element; end

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:8
  def block_argument_names; end

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:7
  def block_body; end

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:3
  def element; end

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:23
  def has_block?; end

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:35
  def lambda_literal?; end

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:5
  def method_name; end

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:10
  def name; end

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:4
  def receiver; end

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:27
  def receiver_element; end

  private

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:41
  def call_element; end

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:60
  def set_arguments; end

  # TODO: write specs for lambdas and procs
  #
  # pkg:gem/fasterer#lib/fasterer/method_call.rb:75
  def set_block_argument_names; end

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:70
  def set_block_body; end

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:64
  def set_block_presence; end

  # TODO: explanation
  #
  # pkg:gem/fasterer#lib/fasterer/method_call.rb:43
  def set_call_element; end

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:56
  def set_method_name; end

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:52
  def set_receiver; end
end

# pkg:gem/fasterer#lib/fasterer/scanners/method_call_scanner.rb:6
class Fasterer::MethodCallScanner
  include ::Fasterer::Offensive

  # pkg:gem/fasterer#lib/fasterer/scanners/method_call_scanner.rb:11
  def initialize(element); end

  # pkg:gem/fasterer#lib/fasterer/scanners/method_call_scanner.rb:9
  def element; end

  # pkg:gem/fasterer#lib/fasterer/scanners/method_call_scanner.rb:16
  def method_call; end

  private

  # pkg:gem/fasterer#lib/fasterer/scanners/method_call_scanner.rb:95
  def check_each_offense; end

  # pkg:gem/fasterer#lib/fasterer/scanners/method_call_scanner.rb:77
  def check_each_with_index_offense; end

  # pkg:gem/fasterer#lib/fasterer/scanners/method_call_scanner.rb:119
  def check_fetch_offense; end

  # pkg:gem/fasterer#lib/fasterer/scanners/method_call_scanner.rb:81
  def check_first_offense; end

  # pkg:gem/fasterer#lib/fasterer/scanners/method_call_scanner.rb:108
  def check_flatten_offense; end

  # pkg:gem/fasterer#lib/fasterer/scanners/method_call_scanner.rb:58
  def check_gsub_offense; end

  # pkg:gem/fasterer#lib/fasterer/scanners/method_call_scanner.rb:155
  def check_last_offense; end

  # pkg:gem/fasterer#lib/fasterer/scanners/method_call_scanner.rb:144
  def check_merge_bang_offense; end

  # pkg:gem/fasterer#lib/fasterer/scanners/method_call_scanner.rb:51
  def check_module_eval_offense; end

  # pkg:gem/fasterer#lib/fasterer/scanners/method_call_scanner.rb:22
  def check_offense; end

  # pkg:gem/fasterer#lib/fasterer/scanners/method_call_scanner.rb:164
  def check_range_include_offense; end

  # pkg:gem/fasterer#lib/fasterer/scanners/method_call_scanner.rb:71
  def check_sort_offense; end

  # Need to refactor, fukken complicated conditions.
  #
  # pkg:gem/fasterer#lib/fasterer/scanners/method_call_scanner.rb:126
  def check_symbol_to_proc; end
end

# pkg:gem/fasterer#lib/fasterer/method_definition.rb:2
class Fasterer::MethodDefinition
  # pkg:gem/fasterer#lib/fasterer/method_definition.rb:11
  def initialize(element); end

  # pkg:gem/fasterer#lib/fasterer/method_definition.rb:7
  def arguments; end

  # pkg:gem/fasterer#lib/fasterer/method_definition.rb:5
  def block_argument_name; end

  # pkg:gem/fasterer#lib/fasterer/method_definition.rb:6
  def body; end

  # pkg:gem/fasterer#lib/fasterer/method_definition.rb:3
  def element; end

  # pkg:gem/fasterer#lib/fasterer/method_definition.rb:19
  def has_block?; end

  # for testing purposes
  #
  # pkg:gem/fasterer#lib/fasterer/method_definition.rb:4
  def method_name; end

  # pkg:gem/fasterer#lib/fasterer/method_definition.rb:9
  def name; end

  # pkg:gem/fasterer#lib/fasterer/method_definition.rb:23
  def setter?; end

  private

  # pkg:gem/fasterer#lib/fasterer/method_definition.rb:29
  def arguments_element; end

  # pkg:gem/fasterer#lib/fasterer/method_definition.rb:53
  def last_argument_element; end

  # pkg:gem/fasterer#lib/fasterer/method_definition.rb:37
  def set_arguments; end

  # pkg:gem/fasterer#lib/fasterer/method_definition.rb:47
  def set_block_argument_name; end

  # pkg:gem/fasterer#lib/fasterer/method_definition.rb:43
  def set_body; end

  # pkg:gem/fasterer#lib/fasterer/method_definition.rb:33
  def set_method_name; end
end

# pkg:gem/fasterer#lib/fasterer/method_definition.rb:58
class Fasterer::MethodDefinitionArgument
  # pkg:gem/fasterer#lib/fasterer/method_definition.rb:61
  def initialize(element); end

  # pkg:gem/fasterer#lib/fasterer/method_definition.rb:71
  def default_argument?; end

  # pkg:gem/fasterer#lib/fasterer/method_definition.rb:59
  def element; end

  # pkg:gem/fasterer#lib/fasterer/method_definition.rb:75
  def keyword_argument?; end

  # pkg:gem/fasterer#lib/fasterer/method_definition.rb:59
  def name; end

  # pkg:gem/fasterer#lib/fasterer/method_definition.rb:67
  def regular_argument?; end

  # pkg:gem/fasterer#lib/fasterer/method_definition.rb:59
  def type; end

  private

  # pkg:gem/fasterer#lib/fasterer/method_definition.rb:85
  def set_argument_type; end

  # pkg:gem/fasterer#lib/fasterer/method_definition.rb:81
  def set_name; end
end

# pkg:gem/fasterer#lib/fasterer/scanners/method_definition_scanner.rb:7
class Fasterer::MethodDefinitionScanner
  include ::Fasterer::Offensive

  # pkg:gem/fasterer#lib/fasterer/scanners/method_definition_scanner.rb:12
  def initialize(element); end

  # pkg:gem/fasterer#lib/fasterer/scanners/method_definition_scanner.rb:10
  def element; end

  private

  # pkg:gem/fasterer#lib/fasterer/scanners/method_definition_scanner.rb:19
  def check_offense; end

  # pkg:gem/fasterer#lib/fasterer/scanners/method_definition_scanner.rb:42
  def method_definition; end

  # pkg:gem/fasterer#lib/fasterer/scanners/method_definition_scanner.rb:27
  def scan_block_call_offense; end

  # pkg:gem/fasterer#lib/fasterer/scanners/method_definition_scanner.rb:54
  def scan_getter_and_setter_offense; end

  # pkg:gem/fasterer#lib/fasterer/scanners/method_definition_scanner.rb:73
  def scan_getter_offense; end

  # pkg:gem/fasterer#lib/fasterer/scanners/method_definition_scanner.rb:58
  def scan_setter_offense; end

  # pkg:gem/fasterer#lib/fasterer/scanners/method_definition_scanner.rb:46
  def traverse_tree(sexp_tree, &block); end
end

# pkg:gem/fasterer#lib/fasterer/offense.rb:2
class Fasterer::Offense
  # pkg:gem/fasterer#lib/fasterer/offense.rb:8
  def initialize(offense_name, line_number); end

  # pkg:gem/fasterer#lib/fasterer/offense.rb:14
  def explanation; end

  # pkg:gem/fasterer#lib/fasterer/offense.rb:6
  def line; end

  # pkg:gem/fasterer#lib/fasterer/offense.rb:3
  def line_number; end

  # pkg:gem/fasterer#lib/fasterer/offense.rb:5
  def name; end

  # pkg:gem/fasterer#lib/fasterer/offense.rb:3
  def offense_name; end
end

# pkg:gem/fasterer#lib/fasterer/offense.rb:18
Fasterer::Offense::EXPLANATIONS = T.let(T.unsafe(nil), Hash)

# pkg:gem/fasterer#lib/fasterer/offense_collector.rb:4
class Fasterer::OffenseCollector
  extend ::Forwardable

  # pkg:gem/fasterer#lib/fasterer/offense_collector.rb:7
  def initialize; end

  # pkg:gem/fasterer#lib/fasterer/offense_collector.rb:11
  def [](offense_name); end

  # pkg:gem/fasterer#lib/fasterer/offense_collector.rb:15
  def any?(*args, **_arg1, &block); end

  # pkg:gem/fasterer#lib/fasterer/offense_collector.rb:15
  def count(*args, **_arg1, &block); end

  # pkg:gem/fasterer#lib/fasterer/offense_collector.rb:15
  def each(*args, **_arg1, &block); end

  # pkg:gem/fasterer#lib/fasterer/offense_collector.rb:15
  def group_by(*args, **_arg1, &block); end

  # pkg:gem/fasterer#lib/fasterer/offense_collector.rb:15
  def push(*args, **_arg1, &block); end
end

# pkg:gem/fasterer#lib/fasterer/scanners/offensive.rb:4
module Fasterer::Offensive
  # pkg:gem/fasterer#lib/fasterer/scanners/offensive.rb:5
  def offense; end

  # pkg:gem/fasterer#lib/fasterer/scanners/offensive.rb:5
  def offense=(_arg0); end

  # pkg:gem/fasterer#lib/fasterer/scanners/offensive.rb:11
  def offense_detected?; end

  # pkg:gem/fasterer#lib/fasterer/scanners/offensive.rb:7
  def offensive?; end

  private

  # pkg:gem/fasterer#lib/fasterer/scanners/offensive.rb:15
  def add_offense(offense_name, element_line_number = T.unsafe(nil)); end

  # pkg:gem/fasterer#lib/fasterer/scanners/offensive.rb:19
  def check_offense; end
end

# pkg:gem/fasterer#lib/fasterer/parser.rb:4
class Fasterer::Parser
  class << self
    # pkg:gem/fasterer#lib/fasterer/parser.rb:7
    def parse(ruby_code); end
  end
end

# pkg:gem/fasterer#lib/fasterer/parser.rb:5
Fasterer::Parser::PARSER_CLASS = RubyParser

# pkg:gem/fasterer#lib/fasterer/method_call.rb:124
class Fasterer::Primitive
  # pkg:gem/fasterer#lib/fasterer/method_call.rb:127
  def initialize(element); end

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:139
  def array?; end

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:125
  def element; end

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:135
  def range?; end

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:131
  def type; end
end

# For now, used for determening if the
# receiver is a reference or a method call.
#
# pkg:gem/fasterer#lib/fasterer/method_call.rb:84
class Fasterer::ReceiverFactory
  class << self
    # pkg:gem/fasterer#lib/fasterer/method_call.rb:85
    def new(receiver_info); end
  end
end

# pkg:gem/fasterer#lib/fasterer/rescue_call.rb:2
class Fasterer::RescueCall
  # pkg:gem/fasterer#lib/fasterer/rescue_call.rb:6
  def initialize(element); end

  # pkg:gem/fasterer#lib/fasterer/rescue_call.rb:3
  def element; end

  # pkg:gem/fasterer#lib/fasterer/rescue_call.rb:4
  def rescue_classes; end

  private

  # pkg:gem/fasterer#lib/fasterer/rescue_call.rb:14
  def set_rescue_classes; end
end

# pkg:gem/fasterer#lib/fasterer/scanners/rescue_call_scanner.rb:6
class Fasterer::RescueCallScanner
  include ::Fasterer::Offensive

  # pkg:gem/fasterer#lib/fasterer/scanners/rescue_call_scanner.rb:11
  def initialize(element); end

  # pkg:gem/fasterer#lib/fasterer/scanners/rescue_call_scanner.rb:9
  def element; end

  private

  # pkg:gem/fasterer#lib/fasterer/scanners/rescue_call_scanner.rb:18
  def check_offense; end

  # pkg:gem/fasterer#lib/fasterer/scanners/rescue_call_scanner.rb:24
  def rescue_call; end
end

# pkg:gem/fasterer#lib/fasterer/version.rb:2
Fasterer::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/fasterer#lib/fasterer/method_call.rb:99
class Fasterer::VariableReference
  # pkg:gem/fasterer#lib/fasterer/method_call.rb:102
  def initialize(reference_info); end

  # pkg:gem/fasterer#lib/fasterer/method_call.rb:100
  def name; end
end
