# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rubocop-yard` gem.
# Please instead update this file by running `bin/tapioca gem rubocop-yard`.


# pkg:gem/rubocop-yard#lib/rubocop/yard/version.rb:3
module RuboCop; end

# pkg:gem/rubocop-yard#lib/rubocop/cop/yard/helper.rb:4
module RuboCop::Cop; end

# pkg:gem/rubocop-yard#lib/rubocop/cop/yard/helper.rb:5
module RuboCop::Cop::YARD; end

# @example EnforcedStyle short
#
#   # bad
#   # @param [Hash{KeyType => ValueType}]
#
#   # bad
#   # @param [Array(String)]
#
#   # bad
#   # @param [Array<String>]
#
#   # good
#   # @param [{KeyType => ValueType}]
#
#   # good
#   # @param [(String)]
#
#   # good
#   # @param [<String>]
#
# @example EnforcedStyle long (default)
#   # bad
#   # @param [{KeyType => ValueType}]
#
#   # bad
#   # @param [(String)]
#
#   # bad
#   # @param [<String>]
#
#   # good
#   # @param [Hash{KeyType => ValueType}]
#
#   # good
#   # @param [Array(String)]
#
#   # good
#   # @param [Array<String>]
#
# pkg:gem/rubocop-yard#lib/rubocop/cop/yard/collection_style.rb:44
class RuboCop::Cop::YARD::CollectionStyle < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::YARD::Helper
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::Cop::ConfigurableEnforcedStyle
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/collection_style.rb:50
  def on_new_investigation; end

  private

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/collection_style.rb:77
  def bad_style; end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/collection_style.rb:61
  def check(comment); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/collection_style.rb:73
  def ignore_whitespace(str); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/collection_style.rb:85
  def include_yard_tag?(comment); end
end

# @example common
#   # bad
#   # @param [Hash<Symbol, String>]
#
#   # bad
#   # @param [Hash(String)]
#
#   # bad
#   # @param [Array{Symbol => String}]
#
#   # good
#   # @param [Hash{Symbol => String}]
#
#   # good
#   # @param [Array(String)]
#
#   # good
#   # @param [Hash{Symbol => String}]
#
# pkg:gem/rubocop-yard#lib/rubocop/cop/yard/collection_type.rb:24
class RuboCop::Cop::YARD::CollectionType < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::YARD::Helper
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::Cop::ConfigurableEnforcedStyle
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/collection_type.rb:30
  def on_new_investigation; end

  private

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/collection_type.rb:42
  def check_mismatch_collection_type(comment, docstring); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/collection_type.rb:48
  def check_mismatch_collection_type_one(comment, types_explainer); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/collection_type.rb:111
  def correct_tag_type(corrector, comment, types_explainer); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/collection_type.rb:115
  def include_yard_tag?(comment); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/collection_type.rb:119
  def tag_range_for_comment(comment); end
end

# pkg:gem/rubocop-yard#lib/rubocop/cop/yard/helper.rb:6
module RuboCop::Cop::YARD::Helper
  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/helper.rb:81
  def build_docstring(preceding_lines); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/helper.rb:22
  def each_types_explainer(docstring, &block); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/helper.rb:7
  def extract_tag_types(tag); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/helper.rb:77
  def inline_comment?(comment); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/helper.rb:18
  def parse_type(type); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/helper.rb:38
  def styled_string(types_explainer); end
end

# @example meaningless tag
#   # bad
#   # @param [String] foo
#   # @option bar baz [String]
#   class Foo
#
#   # bad
#   # @param [String] foo
#   # @option bar baz [String]
#   CONST = 1
#
#   # good
#   class Foo
#
#   # good
#   CONST = 1
#
#   # good (Struct/Data constant assignments accept @param)
#   # @param name [String]
#   # @param age [Integer]
#   Person = Struct.new(:name, :age, keyword_init: true)
#
# pkg:gem/rubocop-yard#lib/rubocop/cop/yard/meaningless_tag.rb:27
class RuboCop::Cop::YARD::MeaninglessTag < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::YARD::Helper
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::Cop::DocumentationComment
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/meaningless_tag.rb:48
  def check(node); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/meaningless_tag.rb:46
  def on_casgn(node); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/meaningless_tag.rb:42
  def on_class(node); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/meaningless_tag.rb:45
  def on_module(node); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/meaningless_tag.rb:35
  def struct_or_data_definition?(param0 = T.unsafe(nil)); end
end

# @example mismatch name
#   # bad
#   # @param [void] baz
#   # @option opt aaa [void]
#   def foo(bar, opts = {})
#   end
#
#   # good
#   # @param [void] bar
#   # @param [Array] arg
#   # @option opts aaa [void]
#   def foo(bar, opts = {}, *arg)
#   end
#
# pkg:gem/rubocop-yard#lib/rubocop/cop/yard/mismatch_name.rb:19
class RuboCop::Cop::YARD::MismatchName < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::YARD::Helper
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::Cop::DocumentationComment
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/mismatch_name.rb:25
  def on_def(node); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/mismatch_name.rb:95
  def on_defs(node); end

  private

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/mismatch_name.rb:173
  def add_offense_to_tag(node, comment, tag); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/mismatch_name.rb:151
  def cop_config_prototype_name; end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/mismatch_name.rb:159
  def each_tags_by_docstring(tag_names, docstring); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/mismatch_name.rb:165
  def find_by_tag(preceding_lines, tag, i); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/mismatch_name.rb:190
  def include_overload_tag?(docstring); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/mismatch_name.rb:120
  def literal_to_yard_type(node); end

  # @param [RuboCop::AST::ArgNode] argument
  #
  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/mismatch_name.rb:100
  def tag_prototype(argument); end
end

# pkg:gem/rubocop-yard#lib/rubocop/cop/yard/tag_type_position.rb:6
class RuboCop::Cop::YARD::TagTypePosition < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::YARD::Helper
  include ::RuboCop::Cop::RangeHelp

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/tag_type_position.rb:10
  def on_new_investigation; end

  private

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/tag_type_position.rb:22
  def check(comment); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/tag_type_position.rb:33
  def include_yard_tag?(comment); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/tag_type_position.rb:37
  def include_yard_tag_type?(comment); end
end

# @example tag type
#   # bad
#   # @param [Integer String]
#
#   # good
#   # @param [Integer, String]
#
# pkg:gem/rubocop-yard#lib/rubocop/cop/yard/tag_type_syntax.rb:12
class RuboCop::Cop::YARD::TagTypeSyntax < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::YARD::Helper
  include ::RuboCop::Cop::RangeHelp

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/tag_type_syntax.rb:16
  def on_new_investigation; end

  private

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/tag_type_syntax.rb:27
  def check(comment); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/tag_type_syntax.rb:38
  def check_syntax_error(comment); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/tag_type_syntax.rb:46
  def include_yard_tag?(comment); end

  # pkg:gem/rubocop-yard#lib/rubocop/cop/yard/tag_type_syntax.rb:50
  def tag_range_for_comment(comment); end
end

# pkg:gem/rubocop-yard#lib/rubocop/yard/version.rb:4
module RuboCop::YARD; end

# pkg:gem/rubocop-yard#lib/rubocop/yard.rb:11
RuboCop::YARD::CONFIG = T.let(T.unsafe(nil), Hash)

# pkg:gem/rubocop-yard#lib/rubocop/yard.rb:10
RuboCop::YARD::CONFIG_DEFAULT = T.let(T.unsafe(nil), Pathname)

# pkg:gem/rubocop-yard#lib/rubocop/yard.rb:7
class RuboCop::YARD::Error < ::StandardError; end

# Your code goes here...
#
# pkg:gem/rubocop-yard#lib/rubocop/yard.rb:9
RuboCop::YARD::PROJECT_ROOT = T.let(T.unsafe(nil), Pathname)

# A plugin that integrates RuboCop Performance with RuboCop's plugin system.
#
# pkg:gem/rubocop-yard#lib/rubocop/yard/plugin.rb:8
class RuboCop::YARD::Plugin < ::LintRoller::Plugin
  # pkg:gem/rubocop-yard#lib/rubocop/yard/plugin.rb:9
  def about; end

  # pkg:gem/rubocop-yard#lib/rubocop/yard/plugin.rb:22
  def rules(_context); end

  # pkg:gem/rubocop-yard#lib/rubocop/yard/plugin.rb:18
  def supported?(context); end
end

# pkg:gem/rubocop-yard#lib/rubocop/yard/version.rb:5
RuboCop::YARD::VERSION = T.let(T.unsafe(nil), String)
