# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `solargraph-rails` gem.
# Please instead update this file by running `bin/tapioca gem solargraph-rails`.


# source://solargraph-rails//lib/solargraph/rails/util.rb#1
module Solargraph
  class << self
    # source://solargraph/0.50.1-904b9304770a59fac393c5cc3cad481e5bdf0fd8/lib/solargraph.rb#53
    def logger; end

    # source://solargraph/0.50.1-904b9304770a59fac393c5cc3cad481e5bdf0fd8/lib/solargraph.rb#61
    def with_clean_env(&block); end
  end
end

# source://solargraph-rails//lib/solargraph/rails/util.rb#2
module Solargraph::Rails; end

# source://solargraph-rails//lib/solargraph/rails/annotate.rb#3
class Solargraph::Rails::Annotate
  # @return [Annotate] a new instance of Annotate
  #
  # source://solargraph-rails//lib/solargraph/rails/annotate.rb#12
  def initialize; end

  # source://solargraph-rails//lib/solargraph/rails/annotate.rb#16
  def process(source_map, ns); end

  class << self
    # source://solargraph-rails//lib/solargraph/rails/annotate.rb#4
    def instance; end

    # source://solargraph-rails//lib/solargraph/rails/annotate.rb#8
    def reset; end
  end
end

# source://solargraph-rails//lib/solargraph/rails/autoload.rb#3
class Solargraph::Rails::Autoload
  # source://solargraph-rails//lib/solargraph/rails/autoload.rb#18
  def namespace_stubs(root_ns, ns); end

  # source://solargraph-rails//lib/solargraph/rails/autoload.rb#8
  def process(source_map, ns, ds); end

  class << self
    # source://solargraph-rails//lib/solargraph/rails/autoload.rb#4
    def instance; end
  end
end

# source://solargraph-rails//lib/solargraph-rails.rb#24
class Solargraph::Rails::Convention < ::Solargraph::Convention::Base
  # source://solargraph-rails//lib/solargraph-rails.rb#25
  def global(yard_map); end

  # source://solargraph-rails//lib/solargraph-rails.rb#36
  def local(source_map); end

  private

  # source://solargraph-rails//lib/solargraph-rails.rb#60
  def run_feature(&block); end
end

# source://solargraph-rails//lib/solargraph/rails/debug.rb#3
class Solargraph::Rails::Debug
  # source://solargraph-rails//lib/solargraph/rails/debug.rb#8
  def run(query); end

  class << self
    # source://solargraph-rails//lib/solargraph/rails/debug.rb#4
    def run(query = T.unsafe(nil)); end
  end
end

# source://solargraph-rails//lib/solargraph/rails/delegate.rb#3
class Solargraph::Rails::Delegate
  # source://solargraph-rails//lib/solargraph/rails/delegate.rb#8
  def process(source_map, ns); end

  class << self
    # source://solargraph-rails//lib/solargraph/rails/delegate.rb#4
    def instance; end
  end
end

# source://solargraph-rails//lib/solargraph/rails/devise.rb#3
class Solargraph::Rails::Devise
  # source://solargraph-rails//lib/solargraph/rails/devise.rb#8
  def process(source_map, ns); end

  private

  # source://solargraph-rails//lib/solargraph/rails/devise.rb#18
  def process_model(source, ns); end

  class << self
    # source://solargraph-rails//lib/solargraph/rails/devise.rb#4
    def instance; end
  end
end

# source://solargraph-rails//lib/solargraph/rails/model.rb#3
class Solargraph::Rails::Model
  # source://solargraph-rails//lib/solargraph/rails/model.rb#92
  def extract_custom_class_name(ast); end

  # source://solargraph-rails//lib/solargraph/rails/model.rb#65
  def plural_association(ns, ast); end

  # source://solargraph-rails//lib/solargraph/rails/model.rb#12
  def process(source_map, ns); end

  # source://solargraph-rails//lib/solargraph/rails/model.rb#79
  def singular_association(ns, ast); end

  class << self
    # source://solargraph-rails//lib/solargraph/rails/model.rb#4
    def instance; end

    # @return [Boolean]
    #
    # source://solargraph-rails//lib/solargraph/rails/model.rb#8
    def valid_filename?(filename); end
  end
end

# source://solargraph-rails//lib/solargraph-rails.rb#20
class Solargraph::Rails::NodeParser
  extend ::Solargraph::Parser::Legacy::ClassMethods
end

# source://solargraph-rails//lib/solargraph/rails/rails_api.rb#3
class Solargraph::Rails::RailsApi
  # source://solargraph-rails//lib/solargraph/rails/rails_api.rb#8
  def global(yard_map); end

  # source://solargraph-rails//lib/solargraph/rails/rails_api.rb#74
  def local(source_map, ns); end

  class << self
    # source://solargraph-rails//lib/solargraph/rails/rails_api.rb#4
    def instance; end
  end
end

# source://solargraph-rails//lib/solargraph/rails/schema.rb#3
class Solargraph::Rails::Schema
  # @return [Schema] a new instance of Schema
  #
  # source://solargraph-rails//lib/solargraph/rails/schema.rb#34
  def initialize; end

  # source://solargraph-rails//lib/solargraph/rails/schema.rb#38
  def process(source_map, ns); end

  private

  # source://solargraph-rails//lib/solargraph/rails/schema.rb#108
  def extract_schema(ast); end

  # source://solargraph-rails//lib/solargraph/rails/schema.rb#85
  def find_table(source_map, ns); end

  # source://solargraph-rails//lib/solargraph/rails/schema.rb#99
  def infer_table_names(ns); end

  # source://solargraph-rails//lib/solargraph/rails/schema.rb#77
  def schema; end

  class << self
    # source://solargraph-rails//lib/solargraph/rails/schema.rb#26
    def instance; end

    # source://solargraph-rails//lib/solargraph/rails/schema.rb#30
    def reset; end
  end
end

# source://solargraph-rails//lib/solargraph/rails/schema.rb#4
class Solargraph::Rails::Schema::ColumnData < ::Struct
  # Returns the value of attribute ast
  #
  # @return [Object] the current value of ast
  def ast; end

  # Sets the attribute ast
  #
  # @param value [Object] the value to set the attribute ast to.
  # @return [Object] the newly set value
  def ast=(_); end

  # Returns the value of attribute type
  #
  # @return [Object] the current value of type
  def type; end

  # Sets the attribute type
  #
  # @param value [Object] the value to set the attribute type to.
  # @return [Object] the newly set value
  def type=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

# source://solargraph-rails//lib/solargraph/rails/schema.rb#6
Solargraph::Rails::Schema::RUBY_TYPES = T.let(T.unsafe(nil), Hash)

# source://solargraph-rails//lib/solargraph/rails/storage.rb#3
class Solargraph::Rails::Storage
  # source://solargraph-rails//lib/solargraph/rails/storage.rb#8
  def process(source_map, ns); end

  class << self
    # source://solargraph-rails//lib/solargraph/rails/storage.rb#4
    def instance; end
  end
end

# source://solargraph-rails//lib/solargraph/rails/util.rb#3
module Solargraph::Rails::Util
  class << self
    # source://solargraph-rails//lib/solargraph/rails/util.rb#68
    def build_location(ast, path); end

    # source://solargraph-rails//lib/solargraph/rails/util.rb#53
    def build_module_extend(ns, module_name, location); end

    # source://solargraph-rails//lib/solargraph/rails/util.rb#45
    def build_module_include(ns, module_name, location); end

    # source://solargraph-rails//lib/solargraph/rails/util.rb#4
    def build_public_method(ns, name, types: T.unsafe(nil), params: T.unsafe(nil), location: T.unsafe(nil), attribute: T.unsafe(nil), scope: T.unsafe(nil)); end

    # source://solargraph-rails//lib/solargraph/rails/util.rb#61
    def dummy_location(path); end

    # source://solargraph-rails//lib/solargraph/rails/util.rb#80
    def method_return(path, type); end
  end
end

# source://solargraph-rails//lib/solargraph/rails/version.rb#3
Solargraph::Rails::VERSION = T.let(T.unsafe(nil), String)

# source://solargraph-rails//lib/solargraph/rails/walker.rb#3
class Solargraph::Rails::Walker
  # @return [Walker] a new instance of Walker
  #
  # source://solargraph-rails//lib/solargraph/rails/walker.rb#68
  def initialize(ast, comments = T.unsafe(nil)); end

  # Returns the value of attribute ast.
  #
  # source://solargraph-rails//lib/solargraph/rails/walker.rb#67
  def ast; end

  # Returns the value of attribute comments.
  #
  # source://solargraph-rails//lib/solargraph/rails/walker.rb#67
  def comments; end

  # source://solargraph-rails//lib/solargraph/rails/walker.rb#74
  def on(node_type, args = T.unsafe(nil), &block); end

  # source://solargraph-rails//lib/solargraph/rails/walker.rb#78
  def walk; end

  private

  # source://solargraph-rails//lib/solargraph/rails/walker.rb#84
  def traverse(node); end

  class << self
    # source://solargraph-rails//lib/solargraph/rails/walker.rb#63
    def from_source(source); end

    # https://github.com/castwide/solargraph/issues/522
    #
    # source://solargraph-rails//lib/solargraph/rails/walker.rb#53
    def normalize_ast(source); end
  end
end

# source://solargraph-rails//lib/solargraph/rails/walker.rb#4
class Solargraph::Rails::Walker::Hook
  # @return [Hook] a new instance of Hook
  #
  # source://solargraph-rails//lib/solargraph/rails/walker.rb#6
  def initialize(node_type, args, &block); end

  # Returns the value of attribute node_type.
  #
  # source://solargraph-rails//lib/solargraph/rails/walker.rb#5
  def node_type; end

  # source://solargraph-rails//lib/solargraph/rails/walker.rb#12
  def visit(node); end

  private

  # source://solargraph-rails//lib/solargraph/rails/walker.rb#41
  def match_children(children, args = T.unsafe(nil)); end

  # @return [Boolean]
  #
  # source://solargraph-rails//lib/solargraph/rails/walker.rb#26
  def matches?(node); end
end
