# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `undercover` gem.
# Please instead update this file by running `bin/tapioca gem undercover`.


# source://undercover//lib/undercover/root_to_relative_paths.rb#3
module Undercover; end

# source://undercover//lib/undercover/cli.rb#7
module Undercover::CLI
  class << self
    # source://undercover//lib/undercover/cli.rb#44
    def changeset(opts); end

    # source://undercover//lib/undercover/cli.rb#17
    def run(args); end

    # source://undercover//lib/undercover/cli.rb#24
    def run_report(opts); end

    # source://undercover//lib/undercover/cli.rb#38
    def syntax_version(version); end
  end
end

# TODO: Report calls >parser< for each file instead of
# traversing the whole project at first!
#
# source://undercover//lib/undercover/cli.rb#11
Undercover::CLI::WARNINGS_TO_S = T.let(T.unsafe(nil), Hash)

# Base class for different kinds of input
#
# source://undercover//lib/undercover/changeset.rb#8
class Undercover::Changeset
  # @return [Changeset] a new instance of Changeset
  #
  # source://undercover//lib/undercover/changeset.rb#11
  def initialize(dir, compare_base = T.unsafe(nil), filter_set = T.unsafe(nil)); end

  # source://undercover//lib/undercover/changeset.rb#33
  def each_changed_line; end

  # source://undercover//lib/undercover/changeset.rb#29
  def file_paths; end

  # source://undercover//lib/undercover/changeset.rb#19
  def last_modified; end

  # source://undercover//lib/undercover/changeset.rb#46
  def validate(lcov_report_path); end

  private

  # Returns the value of attribute compare_base.
  #
  # source://undercover//lib/undercover/changeset.rb#73
  def compare_base; end

  # source://undercover//lib/undercover/changeset.rb#61
  def compare_base_obj; end

  # Returns the value of attribute filter_set.
  #
  # source://undercover//lib/undercover/changeset.rb#73
  def filter_set; end

  # Diffs `head` or `head` + `compare_base` (if exists),
  # as it makes sense to run Undercover with the most recent file versions
  #
  # source://undercover//lib/undercover/changeset.rb#56
  def full_diff; end

  # source://undercover//lib/undercover/changeset.rb#69
  def head; end

  # Returns the value of attribute repo.
  #
  # source://undercover//lib/undercover/changeset.rb#73
  def repo; end
end

# source://undercover//lib/undercover/changeset.rb#9
Undercover::Changeset::T_ZERO = T.let(T.unsafe(nil), Time)

# source://undercover//lib/undercover/filter_set.rb#4
class Undercover::FilterSet
  # @return [FilterSet] a new instance of FilterSet
  #
  # source://undercover//lib/undercover/filter_set.rb#7
  def initialize(allow_filters, reject_filters); end

  # Returns the value of attribute allow_filters.
  #
  # source://undercover//lib/undercover/filter_set.rb#5
  def allow_filters; end

  # @return [Boolean]
  #
  # source://undercover//lib/undercover/filter_set.rb#12
  def include?(filepath); end

  # Returns the value of attribute reject_filters.
  #
  # source://undercover//lib/undercover/filter_set.rb#5
  def reject_filters; end
end

# source://undercover//lib/undercover/formatter.rb#4
class Undercover::Formatter
  # @return [Formatter] a new instance of Formatter
  #
  # source://undercover//lib/undercover/formatter.rb#5
  def initialize(results); end

  # source://undercover//lib/undercover/formatter.rb#9
  def to_s; end

  private

  # source://undercover//lib/undercover/formatter.rb#17
  def formatted_warnings; end

  # source://undercover//lib/undercover/formatter.rb#37
  def pad_size; end

  # source://undercover//lib/undercover/formatter.rb#26
  def success; end

  # source://undercover//lib/undercover/formatter.rb#31
  def warnings_header; end
end

# source://undercover//lib/undercover/lcov_parser.rb#6
class Undercover::LcovParseError < ::StandardError; end

# source://undercover//lib/undercover/lcov_parser.rb#8
class Undercover::LcovParser
  include ::Undercover::RootToRelativePaths

  # @return [LcovParser] a new instance of LcovParser
  #
  # source://undercover//lib/undercover/lcov_parser.rb#13
  def initialize(lcov_io, opts); end

  # source://undercover//lib/undercover/lcov_parser.rb#30
  def coverage(filepath); end

  # Returns the value of attribute io.
  #
  # source://undercover//lib/undercover/lcov_parser.rb#11
  def io; end

  # source://undercover//lib/undercover/lcov_parser.rb#24
  def parse; end

  # @return [Boolean]
  #
  # source://undercover//lib/undercover/lcov_parser.rb#55
  def skipped?(_filepath, _line_no); end

  # Returns the value of attribute source_files.
  #
  # source://undercover//lib/undercover/lcov_parser.rb#11
  def source_files; end

  # source://undercover//lib/undercover/lcov_parser.rb#46
  def total_branch_coverage; end

  # source://undercover//lib/undercover/lcov_parser.rb#37
  def total_coverage; end

  private

  # source://undercover//lib/undercover/lcov_parser.rb#63
  def parse_line(line); end

  class << self
    # source://undercover//lib/undercover/lcov_parser.rb#19
    def parse(lcov_report_path, opts = T.unsafe(nil)); end
  end
end

# source://undercover//lib/undercover/options.rb#7
class Undercover::Options
  # @return [Options] a new instance of Options
  #
  # source://undercover//lib/undercover/options.rb#48
  def initialize; end

  # Returns the value of attribute compare.
  #
  # source://undercover//lib/undercover/options.rb#36
  def compare; end

  # Sets the attribute compare
  #
  # @param value the value to set the attribute compare to.
  #
  # source://undercover//lib/undercover/options.rb#36
  def compare=(_arg0); end

  # Returns the value of attribute file_scope.
  #
  # source://undercover//lib/undercover/options.rb#36
  def file_scope; end

  # Sets the attribute file_scope
  #
  # @param value the value to set the attribute file_scope to.
  #
  # source://undercover//lib/undercover/options.rb#36
  def file_scope=(_arg0); end

  # Returns the value of attribute git_dir.
  #
  # source://undercover//lib/undercover/options.rb#36
  def git_dir; end

  # Sets the attribute git_dir
  #
  # @param value the value to set the attribute git_dir to.
  #
  # source://undercover//lib/undercover/options.rb#36
  def git_dir=(_arg0); end

  # Returns the value of attribute glob_allow_filters.
  #
  # source://undercover//lib/undercover/options.rb#36
  def glob_allow_filters; end

  # Sets the attribute glob_allow_filters
  #
  # @param value the value to set the attribute glob_allow_filters to.
  #
  # source://undercover//lib/undercover/options.rb#36
  def glob_allow_filters=(_arg0); end

  # Returns the value of attribute glob_reject_filters.
  #
  # source://undercover//lib/undercover/options.rb#36
  def glob_reject_filters; end

  # Sets the attribute glob_reject_filters
  #
  # @param value the value to set the attribute glob_reject_filters to.
  #
  # source://undercover//lib/undercover/options.rb#36
  def glob_reject_filters=(_arg0); end

  # Returns the value of attribute lcov.
  #
  # source://undercover//lib/undercover/options.rb#36
  def lcov; end

  # Sets the attribute lcov
  #
  # @param value the value to set the attribute lcov to.
  #
  # source://undercover//lib/undercover/options.rb#36
  def lcov=(_arg0); end

  # Returns the value of attribute max_warnings_limit.
  #
  # source://undercover//lib/undercover/options.rb#36
  def max_warnings_limit; end

  # Sets the attribute max_warnings_limit
  #
  # @param value the value to set the attribute max_warnings_limit to.
  #
  # source://undercover//lib/undercover/options.rb#36
  def max_warnings_limit=(_arg0); end

  # source://undercover//lib/undercover/options.rb#60
  def parse(args); end

  # Returns the value of attribute path.
  #
  # source://undercover//lib/undercover/options.rb#36
  def path; end

  # Sets the attribute path
  #
  # @param value the value to set the attribute path to.
  #
  # source://undercover//lib/undercover/options.rb#36
  def path=(_arg0); end

  # Returns the value of attribute run_mode.
  #
  # source://undercover//lib/undercover/options.rb#36
  def run_mode; end

  # Sets the attribute run_mode
  #
  # @param value the value to set the attribute run_mode to.
  #
  # source://undercover//lib/undercover/options.rb#36
  def run_mode=(_arg0); end

  # Returns the value of attribute simplecov_resultset.
  #
  # source://undercover//lib/undercover/options.rb#36
  def simplecov_resultset; end

  # Sets the attribute simplecov_resultset
  #
  # @param value the value to set the attribute simplecov_resultset to.
  #
  # source://undercover//lib/undercover/options.rb#36
  def simplecov_resultset=(_arg0); end

  # Returns the value of attribute syntax_version.
  #
  # source://undercover//lib/undercover/options.rb#36
  def syntax_version; end

  # Sets the attribute syntax_version
  #
  # @param value the value to set the attribute syntax_version to.
  #
  # source://undercover//lib/undercover/options.rb#36
  def syntax_version=(_arg0); end

  private

  # source://undercover//lib/undercover/options.rb#104
  def args_from_options_file(path); end

  # source://undercover//lib/undercover/options.rb#96
  def build_opts(args); end

  # source://undercover//lib/undercover/options.rb#140
  def compare_option(parser); end

  # source://undercover//lib/undercover/options.rb#173
  def file_filters(parser); end

  # source://undercover//lib/undercover/options.rb#133
  def git_dir_option(parser); end

  # source://undercover//lib/undercover/options.rb#168
  def guess_lcov_path; end

  # source://undercover//lib/undercover/options.rb#162
  def guess_resultset_path; end

  # source://undercover//lib/undercover/options.rb#114
  def lcov_path_option(parser); end

  # source://undercover//lib/undercover/options.rb#155
  def max_warnings_limit_option(parser); end

  # source://undercover//lib/undercover/options.rb#100
  def project_options; end

  # source://undercover//lib/undercover/options.rb#110
  def project_options_file; end

  # source://undercover//lib/undercover/options.rb#127
  def project_path_option(parser); end

  # source://undercover//lib/undercover/options.rb#120
  def resultset_path_option(parser); end

  # source://undercover//lib/undercover/options.rb#147
  def ruby_syntax_option(parser); end
end

# source://undercover//lib/undercover/options.rb#34
Undercover::Options::DEFAULT_FILE_EXCLUDE_GLOBS = T.let(T.unsafe(nil), Array)

# source://undercover//lib/undercover/options.rb#33
Undercover::Options::DEFAULT_FILE_INCLUDE_GLOBS = T.let(T.unsafe(nil), Array)

# source://undercover//lib/undercover/options.rb#11
Undercover::Options::DIFF_TRIGGER_LINE = T.let(T.unsafe(nil), Symbol)

# source://undercover//lib/undercover/options.rb#8
Undercover::Options::DIFF_TRIGGER_MODE = T.let(T.unsafe(nil), Array)

# source://undercover//lib/undercover/options.rb#22
Undercover::Options::FILE_SCOPE = T.let(T.unsafe(nil), Array)

# source://undercover//lib/undercover/options.rb#26
Undercover::Options::FILE_SCOPE_EXTENDED = T.let(T.unsafe(nil), Symbol)

# source://undercover//lib/undercover.rb#22
class Undercover::Report
  extend ::Forwardable

  # Initializes a new Undercover::Report
  #
  # @param changeset [Undercover::Changeset]
  # @param opts [Undercover::Options]
  # @return [Report] a new instance of Report
  #
  # source://undercover//lib/undercover.rb#38
  def initialize(changeset, opts); end

  # source://undercover//lib/undercover.rb#92
  def all_results; end

  # source://undercover//lib/undercover.rb#53
  def build; end

  # source://undercover//lib/undercover.rb#86
  def build_warnings; end

  # Returns the value of attribute changeset.
  #
  # source://undercover//lib/undercover.rb#26
  def changeset; end

  # Returns the value of attribute code_dir.
  #
  # source://undercover//lib/undercover.rb#26
  def code_dir; end

  # Returns the value of attribute filter_set.
  #
  # source://undercover//lib/undercover.rb#26
  def filter_set; end

  # source://undercover//lib/undercover.rb#96
  def flagged_results; end

  # source://undercover//lib/undercover.rb#100
  def inspect; end

  # Returns the value of attribute lcov.
  #
  # source://undercover//lib/undercover.rb#26
  def lcov; end

  # Returns the value of attribute max_warnings_limit.
  #
  # source://undercover//lib/undercover.rb#26
  def max_warnings_limit; end

  # Returns the value of attribute results.
  #
  # source://undercover//lib/undercover.rb#26
  def results; end

  # Returns the value of attribute simplecov_resultset.
  #
  # source://undercover//lib/undercover.rb#26
  def simplecov_resultset; end

  # source://undercover//lib/undercover.rb#100
  def to_s; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def validate(*args, **_arg1, &block); end

  private

  # @return [Boolean]
  #
  # source://undercover//lib/undercover.rb#130
  def include_file?(filepath); end

  # source://undercover//lib/undercover.rb#110
  def load_and_parse_file(filepath); end

  # Returns the value of attribute loaded_files.
  #
  # source://undercover//lib/undercover.rb#107
  def loaded_files; end
end

# source://undercover//lib/undercover/result.rb#6
class Undercover::Result
  extend ::Forwardable

  # @return [Result] a new instance of Result
  #
  # source://undercover//lib/undercover/result.rb#14
  def initialize(node, coverage_adapter, file_path); end

  # Returns the value of attribute coverage.
  #
  # source://undercover//lib/undercover/result.rb#9
  def coverage; end

  # Returns the value of attribute coverage_adapter.
  #
  # source://undercover//lib/undercover/result.rb#9
  def coverage_adapter; end

  # Method `coverage_f` returns the total coverage of this Undercover::Result
  # as a % value, taking into account missing branches. Line coverage will be counted
  # as 0 if any branch is untested.
  #
  # source://undercover//lib/undercover/result.rb#58
  def coverage_f; end

  # Returns the value of attribute file_path.
  #
  # source://undercover//lib/undercover/result.rb#9
  def file_path; end

  # source://undercover//lib/undercover/result.rb#125
  def file_path_with_lines; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def first_line(*args, **_arg1, &block); end

  # source://undercover//lib/undercover/result.rb#32
  def flag; end

  # @return [Boolean]
  #
  # source://undercover//lib/undercover/result.rb#36
  def flagged?; end

  # source://undercover//lib/undercover/result.rb#129
  def inspect; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def last_line(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def name(*args, **_arg1, &block); end

  # Returns the value of attribute node.
  #
  # source://undercover//lib/undercover/result.rb#9
  def node; end

  # TODO: move to formatter interface instead!
  #
  # source://undercover//lib/undercover/result.rb#100
  def pretty_print; end

  # TODO: create a formatter interface instead and add some tests.
  # TODO: re-enable rubocops
  #
  # Zips coverage data (that doesn't include any non-code lines) with
  # full source for given code fragment (this includes non-code lines!)
  #
  # source://undercover//lib/undercover/result.rb#86
  def pretty_print_lines; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def skipped?(*args, **_arg1, &block); end

  # source://undercover//lib/undercover/result.rb#129
  def to_s; end

  # @return [Boolean]
  #
  # source://undercover//lib/undercover/result.rb#40
  def uncovered?(line_no); end

  private

  # source://undercover//lib/undercover/result.rb#138
  def count_covered_branches(line_number); end
end

# source://undercover//lib/undercover/root_to_relative_paths.rb#4
module Undercover::RootToRelativePaths
  # Needed if undercover is running inside nested subdirectories (e.g. in a monorepo app), where
  # the git paths are rooted deeper than the paths in the coverage report.
  # If that is the case, trim the git filepath to match the local relative path, assumming undercover is
  # running in the correct directory (has to be equal to SimpleCov.root for paths to match)
  #
  # @param filepath [String]
  # @return String
  #
  # source://undercover//lib/undercover/root_to_relative_paths.rb#11
  def fix_relative_filepath(filepath); end
end

# source://undercover//lib/undercover/simplecov_result_adapter.rb#6
class Undercover::SimplecovResultAdapter
  include ::Undercover::RootToRelativePaths

  # @param simplecov_result [SimpleCov::Result]
  # @return [SimplecovResultAdapter] a new instance of SimplecovResultAdapter
  #
  # source://undercover//lib/undercover/simplecov_result_adapter.rb#23
  def initialize(simplecov_result, opts); end

  # @param filepath [String]
  # @return Array tuples (lines) and quadruples (branches) compatible with LcovParser
  #
  # source://undercover//lib/undercover/simplecov_result_adapter.rb#30
  def coverage(filepath); end

  # Returns the value of attribute simplecov_result.
  #
  # source://undercover//lib/undercover/simplecov_result_adapter.rb#9
  def simplecov_result; end

  # @return [Boolean]
  #
  # source://undercover//lib/undercover/simplecov_result_adapter.rb#46
  def skipped?(filepath, line_no); end

  # source://undercover//lib/undercover/simplecov_result_adapter.rb#55
  def total_branch_coverage; end

  # unused for now
  #
  # source://undercover//lib/undercover/simplecov_result_adapter.rb#54
  def total_coverage; end

  private

  # source://undercover//lib/undercover/simplecov_result_adapter.rb#59
  def find_file(filepath); end

  class << self
    # @param file [File] JSON file supplied by SimpleCov::Formatter::Undercover
    # @raise [ArgumentError]
    # @return SimplecovResultAdapter
    #
    # source://undercover//lib/undercover/simplecov_result_adapter.rb#13
    def parse(file, opts = T.unsafe(nil)); end
  end
end

# source://undercover//lib/undercover/version.rb#4
Undercover::VERSION = T.let(T.unsafe(nil), String)
