language: ruby
cache: bundler
before_install:
  # https://bundler.io/blog/2019/05/14/
  #   solutions-for-cant-find-gem-bundler-with-executable-bundle.html
  - gem update --system
  - gem install bundler
rvm:
  # JRuby error with native code build - possibly can be overcome?
  # checking for main() in -lstdc++... RuntimeError: The compiler failed to generate
  # https://travis-ci.com/apiology/pronto-punchlist/jobs/264907931
  # - jruby-head
  - ruby-head
  - ruby-2.7
  - ruby-2.6
  - ruby-2.5
  - ruby-2.4
