version: 2
jobs:
  build:
    working_directory: ~/checkoff
    docker:
      - image: apiology/circleci-ruby:latest
    steps:
      - checkout
      - type: cache-restore
        key: checkoff-{{ checksum "Gemfile.lock" }}
      - run: bundle install
      - run: bundle exec rake --jobs=4 test
      - run: bundle exec rake --jobs=4 quality
      - type: cache-save
        key: checkoff{{ checksum "Gemfile.lock" }}
        paths:
          - "vendor/bundle"
