version: 2
jobs:
  build:
    working_directory: ~/checkoff
    docker:
      - image: apiology/circleci-ruby:latest
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake --jobs=4 test
      - run: bundle exec rake --jobs=4 quality
