# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module Bundler::FetchMetadata; end
module Bundler::MatchMetadata; end
module Parlour::RbiGenerator::Namespace::Mixin::Searchable; end
module Parlour::RbsGenerator::Namespace::Mixin::Searchable; end
module SimpleCov::Formatter::Undercover; end
